server:
    port: 8081
spring:
    application:
        name: user-service
    zipkin:
        base-url: http://localhost:9411
    sleuth:
        sampler:
            probability: 1  #配置采样率  默认的采样比例为: 0.1，即 10%，所设置的值介于 0 到 1 之间，1 则表示全部采集
            rate: 10   #为了使用速率限制采样器,选择每秒间隔接受的trace量，最小数字为0，最大值为2,147,483,647（最大int） 默认为10。
eureka:
    client:
        service-url:
            defaultZone: http://47.100.238.122:8761/eureka
    instance:
        hostname: localhost
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
feign:
    hystrix:
        enabled: true # 开启熔断
management:
    endpoints:
        web:
            exposure:
                include: '*'