server:
    port: 8081
spring:
    application:
        name: eureka-client-b
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
        instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
        hostname: localhost
        lease-renewal-interval-in-seconds: 10