server:
    port: 8081
spring:
    application:
        name: user-service
eureka:
    client:
        service-url:
            defaultZone: http://47.100.238.122:8761/eureka
# feign只是帮你封装了远程调用的功能  底层还是ribbon 所以我们需要去修改ribbon的时间
ribbon:
    ReadTimeout: 3000 # 给3s超时时间
    ConnectTimeout: 3000 # 链接服务的超时时间
logging:
    level:
        com.powernode.feign.UserOrderFeign: debug  # 我需要答应这个接口下面的日志