server:
    port: 8080
spring:
    application:
        name: nacos-client-a
    cloud:
        nacos: # 如果不指定命名空间会默认注册到public里面去 如果没有指定分组 会注册到DEFAULT_GROUP
            server-addr: localhost:8848 # 往这个地址去注册自己
            username: nacos
            password: nacos
            discovery:
                namespace: f5e847a0-119d-4baa-9dff-4bf15e418a42
                group: A_GROUP
my:
    data: '#{@abc}'